version: '3'
services:
  fastapi:
    build: movies_fast
    image: fastapi_image
    env_file:
      - movies_fast/.env
    expose:
      - "8000"

  etl:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      - discovery.type=single-node
    volumes:
      - etl_data:/usr/share/elasticsearch/data

  redis:
    image: redis:7.0.5
    volumes:
      - redis:/data

  tests:
    build: tests
    env_file:
      - tests/functional/.env
    depends_on:
      - fastapi


volumes:
  etl_data:
  redis: